version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}      
      - run: 
          command: mvn clean install
      - save_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=project-sunbird_sunbird-notification-service -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=/home/circleci/project/service/target/site/jacoco/jacoco.xml

workflows:
  version: 2.1
  workflow:
    jobs:
      - build
