package org.sunbird.telemetry;

public interface JsonKey {
  String ACTOR_ID = "actorId";
  String ACTOR_TYPE = "actorType";
  String CORRELATED_OBJECTS = "correlatedObjects";
  String REQUEST_ID = "requestId";
  String TYPE = "type";
  String SUB_TYPE = "subtype";
  String TARGET_OBJECT = "targetObject";
  String ROLLUP = "rollup";
  String PROPS = "props";
  String STATE = "state";
  String UPDATE = "update";
  String CHANNEL = "channel";
  String ENV = "env";
  String DEVICE_ID = "did";
  String APP_ID = "appId";
  String PDATA_ID = "telemetry_pdata_id";
  String PDATA_PID = "telemetry_pdata_pid";
  String PDATA_VERSION = "telemetry_pdata_ver";
  String QUERY = "query";
  String SORT = "sort";
  String FILTERS = "filters";
  String TOPN = "topn";
  String SIZE = "size";
  String LOG_TYPE = "logType";
  String PARAMS = "params";
  String ERR_TYPE = "errtype";
  String PREV_STATE = "PREV_STATE";
  String PREVSTATE = "prevstate";
  String TELEMETRY_EVENT_TYPE = "telemetryEventType";
  String CONTEXT = "context";
  String RELATION = "relation";
  String USER_ID = "userId";
  String ID = "id";
  String LEVEL = "level";
  String MESSAGE = "message";
  String STACKTRACE = "stacktrace";
  String ERROR = "error";
  String LOG_LEVEL = "logLevel";
  String L1="l1";
  String ERR="err";
  String SYSTEM = "SYSTEM";
}
